#!/bin/bash

if [[ ! "$_PYAV_ACTIVATED" ]]; then
    export here="$(cd "$(dirname "${BASH_SOURCE[0]}")"; pwd)"
    source "$here/activate.sh"
fi

cd "$PYAV_ROOT"

# Skip the rest of the build if it already exists.
if [[ -e "$PYAV_LIBRARY_PREFIX/bin/ffmpeg" ]]; then
    echo "We have a cached build of ffmpeg-$PYAV_LIBRARY; skipping re-build."
    exit 0
fi


mkdir -p "$PYAV_LIBRARY_ROOT"
mkdir -p "$PYAV_LIBRARY_PREFIX"
cd "$PYAV_LIBRARY_ROOT"


# Extract major and minor version from PYAV_LIBRARY
PYAV_LIBRARY_VERSION=$(echo $PYAV_LIBRARY | grep -oP '\d+\.\d+')

# Download and expand the source.
if [[ ! -d $PYAV_LIBRARY ]]; then
    git clone git://source.ffmpeg.org/ffmpeg.git $PYAV_LIBRARY -b release/$PYAV_LIBRARY_VERSION --depth=1  || exit 1
    # git clone https://github.com/FFmpeg/FFmpeg.git $PYAV_LIBRARY

    # Clone Keylost's jetson-ffmpeg
    git clone https://github.com/Keylost/jetson-ffmpeg.git
    cd jetson-ffmpeg
    mkdir build && cd build
    cmake -DLIB_NVBUF=/usr/lib/aarch64-linux-gnu/nvidia/libnvmm_utils.so \
      -DLIB_NVBUFSURFACE=/usr/lib/aarch64-linux-gnu/nvidia/libnvbufsurface.so \
      -DLIB_NVBUFSURFTRANSFORM=/usr/lib/aarch64-linux-gnu/nvidia/libnvbufsurftransform.so \
      -DLIB_NVJPEG=/usr/lib/aarch64-linux-gnu/nvidia/libnvjpeg.so \
      -DLIB_V4L2=/usr/lib/aarch64-linux-gnu/nvidia/libnvv4l2.so \
      ..

    make -j4
    make install
    ldconfig

    cd "$PYAV_LIBRARY_ROOT"
fi
cd $PYAV_LIBRARY

# Apply Keylost's nvmpi patch
wget https://github.com/Keylost/jetson-ffmpeg/raw/master/ffmpeg_patches/ffmpeg${PYAV_LIBRARY_VERSION/../}_nvmpi.patch -O ffmpeg_nvmpi.patch
git apply ffmpeg_nvmpi.patch

echo ./configure
./configure \
    --disable-doc \
    --disable-mmx \
    --disable-optimizations \
    --disable-static \
    --disable-stripping \
    --enable-debug=3 \
    --enable-gpl \
    --enable-version3 \
    --disable-libx264 \
    --enable-libxml2 \
    --enable-shared \
    --enable-nvmpi \
    --prefix="$PYAV_LIBRARY_PREFIX" \
    || exit 2
echo

echo make
make -j4 || exit 3
echo

echo make install
make install || exit 4
echo

echo Build products:
cd ~
find "$PYAV_LIBRARY_PREFIX" -name '*libav*'
